const DEFAULT_API_URL = "http://127.0.0.1:8000/api/v1";

const appEnv = import.meta.env;

export const APP_NAME = appEnv.VITE_APP_NAME ?? "Dinamika Jurnal";

export const BASE_API_URL = appEnv.VITE_BASE_API_URL ?? DEFAULT_API_URL;

/** LOGING */
export const SENTRY_DSN = appEnv.VITE_SENTRY_DSN;
export const GA_ID = appEnv.VITE_GA_ID;

/** ACTIVE COMPANY */
export const LOCAL_STORAGE_COMPANY_KEY =
  appEnv.VITE_LOCAL_STORAGE_COMPANY_KEY ?? "active-company";

/** TEMPLATE */
export const TEMPLATE_IMPORT_PURCHASE = appEnv.VITE_TEMPLATE_IMPORT_PURCHASE;
export const TEMPLATE_IMPORT_SALE = appEnv.VITE_TEMPLATE_IMPORT_SALE;
export const TEMPLATE_IMPORT_CASH_BANK = appEnv.VITE_TEMPLATE_IMPORT_CASH_BANK;
export const TEMPLATE_IMPORT_JOURNAL = appEnv.VITE_TEMPLATE_IMPORT_JOURNAL;

const config = {
  APP_NAME,
  BASE_API_URL,
  SENTRY_DSN,
  GA_ID,
  LOCAL_STORAGE_COMPANY_KEY,

  /** TEMPLATE */
  TEMPLATE_IMPORT_SALE,
  TEMPLATE_IMPORT_PURCHASE,
  TEMPLATE_IMPORT_CASH_BANK,
  TEMPLATE_IMPORT_JOURNAL,
};

export default config;
