import { useCallback, useState } from "react";
import useSWR, { type Fetcher } from "swr";
import type { IGetAllTransactionResponse } from "../interfaces/response.type";
import axiosInstance from "@lib/axios-instance";
import querystring from "query-string";

import useUserStore from "@store/useUserStore";
import { parseMonthAndRange } from "@helpers/date";

export default function useGetAllTransaction() {
  const [search, setSearch] = useState("");
  const [pageNum, setPageNum] = useState(1);
  const [pageLimit, setPageLimit] = useState(10);

  const transactionDate = useUserStore((state) => state.transactionDate);
  const transactionType = useUserStore((state) => state.transactionType);
  const transactionStatus = useUserStore((state) => state.transactionStatus);

  const { start_date, end_date } = parseMonthAndRange(transactionDate);

  const fetcher: Fetcher<IGetAllTransactionResponse, string> = (url) =>
    axiosInstance({ withToken: true, withCompany: true, tokenType: "user" })
      .get(url)
      .then((res) => res.data);

  const qs = querystring.stringify(
    {
      search,
      start_date,
      end_date,
      type: transactionType,
      status: transactionStatus,
      page_limit: pageLimit,
      page: pageNum,
    },
    { skipEmptyString: true, skipNull: true },
  );

  const { data, error } = useSWR(`/transactions?${qs}`, fetcher);

  const onSetSearch = useCallback((search: string) => {
    setSearch(search);
  }, []);

  const DUMMY_DATA: IGetAllTransactionResponse = {
    data: [
      {
        reference_id: 1,
        reference_type: "sales-invoice",
        transaction_date: new Date("2025-03-01"),
        transaction_due_date: new Date("2025-03-31"),
        transaction_number: "INV-001",
        contact: { id: 1, name: "PT Maju Jaya" },
        type: "sales-invoice",
        status: "unpaid",
        amount: 1500000,
        remaining: 1500000,
        description: "Penjualan produk A",
      },
      {
        reference_id: 2,
        reference_type: "sales-invoice",
        transaction_date: new Date("2025-03-02"),
        transaction_due_date: new Date("2025-03-30"),
        transaction_number: "INV-002",
        contact: { id: 2, name: "CV Sumber Rejeki" },
        type: "sales-invoice",
        status: "partially-paid",
        amount: 2000000,
        remaining: 500000,
        description: "Penjualan produk B",
      },
      {
        reference_id: 3,
        reference_type: "payment-receipt",
        transaction_date: new Date("2025-03-03"),
        transaction_due_date: new Date("2025-03-03"),
        transaction_number: "PAY-001",
        contact: { id: 1, name: "PT Maju Jaya" },
        type: "payment-receipt",
        status: "paid",
        amount: 1000000,
        remaining: 0,
        description: "Pembayaran invoice INV-001",
      },
      {
        reference_id: 4,
        reference_type: "purchase-invoice",
        transaction_date: new Date("2025-03-04"),
        transaction_due_date: new Date("2025-04-04"),
        transaction_number: "BILL-001",
        contact: { id: 3, name: "PT Supplier Makmur" },
        type: "purchase-invoice",
        status: "unpaid",
        amount: 3500000,
        remaining: 3500000,
        description: "Pembelian bahan baku",
      },
      {
        reference_id: 5,
        reference_type: "bank-transfer",
        transaction_date: new Date("2025-03-05"),
        transaction_due_date: new Date("2025-03-05"),
        transaction_number: "TRF-001",
        contact: { id: 4, name: "Bank BCA" },
        type: "bank-transfer",
        status: "completed",
        amount: 5000000,
        remaining: 0,
        description: "Transfer antar rekening",
      },
      {
        reference_id: 6,
        reference_type: "expense",
        transaction_date: new Date("2025-03-06"),
        transaction_due_date: new Date("2025-03-06"),
        transaction_number: "EXP-001",
        contact: { id: 5, name: "PLN" },
        type: "expense",
        status: "paid",
        amount: 750000,
        remaining: 0,
        description: "Pembayaran listrik kantor",
      },
      {
        reference_id: 7,
        reference_type: "sales-order",
        transaction_date: new Date("2025-03-07"),
        transaction_due_date: new Date("2025-03-20"),
        transaction_number: "SO-001",
        contact: { id: 6, name: "PT Nusantara Abadi" },
        type: "sales-order",
        status: "approved",
        amount: 4500000,
        remaining: 4500000,
        description: "Pesanan produk C",
      },
      {
        reference_id: 8,
        reference_type: "purchase-order",
        transaction_date: new Date("2025-03-08"),
        transaction_due_date: new Date("2025-03-25"),
        transaction_number: "PO-001",
        contact: { id: 7, name: "PT Bahan Sejahtera" },
        type: "purchase-order",
        status: "pending",
        amount: 6000000,
        remaining: 6000000,
        description: "Pemesanan bahan baku",
      },
      {
        reference_id: 9,
        reference_type: "journal-entry",
        transaction_date: new Date("2025-03-09"),
        transaction_due_date: new Date("2025-03-09"),
        transaction_number: "JE-001",
        contact: { id: 0, name: "System" },
        type: "journal-entry",
        status: "approved",
        amount: 1000000,
        remaining: 0,
        description: "Penyesuaian akhir bulan",
      },
      {
        reference_id: 10,
        reference_type: "receive-money",
        transaction_date: new Date("2025-03-10"),
        transaction_due_date: new Date("2025-03-10"),
        transaction_number: "RM-001",
        contact: { id: 8, name: "Customer Retail" },
        type: "receive-money",
        status: "completed",
        amount: 250000,
        remaining: 0,
        description: "Penerimaan uang tunai",
      },
      {
        reference_id: 11,
        reference_type: "sales-invoice",
        transaction_date: new Date("2025-03-11"),
        transaction_due_date: new Date("2025-04-10"),
        transaction_number: "INV-003",
        contact: { id: 9, name: "PT Global Teknologi" },
        type: "sales-invoice",
        status: "overdue",
        amount: 3200000,
        remaining: 3200000,
        description: "Penjualan perangkat IT",
      },
      {
        reference_id: 12,
        reference_type: "expense",
        transaction_date: new Date("2025-03-12"),
        transaction_due_date: new Date("2025-03-12"),
        transaction_number: "EXP-002",
        contact: { id: 10, name: "Telkom" },
        type: "expense",
        status: "paid",
        amount: 450000,
        remaining: 0,
        description: "Pembayaran internet kantor",
      },
      {
        reference_id: 13,
        reference_type: "bank-transfer",
        transaction_date: new Date("2025-03-13"),
        transaction_due_date: new Date("2025-03-13"),
        transaction_number: "TRF-002",
        contact: { id: 4, name: "Bank BCA" },
        type: "bank-transfer",
        status: "completed",
        amount: 2000000,
        remaining: 0,
        description: "Transfer ke rekening operasional",
      },
      {
        reference_id: 14,
        reference_type: "purchase-invoice",
        transaction_date: new Date("2025-03-14"),
        transaction_due_date: new Date("2025-04-14"),
        transaction_number: "BILL-002",
        contact: { id: 3, name: "PT Supplier Makmur" },
        type: "purchase-invoice",
        status: "partially-paid",
        amount: 4000000,
        remaining: 1500000,
        description: "Pembelian bahan produksi",
      },
      {
        reference_id: 15,
        reference_type: "sales-order",
        transaction_date: new Date("2025-03-15"),
        transaction_due_date: new Date("2025-03-25"),
        transaction_number: "SO-002",
        contact: { id: 11, name: "CV Sukses Bersama" },
        type: "sales-order",
        status: "approved",
        amount: 2800000,
        remaining: 2800000,
        description: "Pesanan produk D",
      },
      {
        reference_id: 16,
        reference_type: "purchase-order",
        transaction_date: new Date("2025-03-16"),
        transaction_due_date: new Date("2025-03-30"),
        transaction_number: "PO-002",
        contact: { id: 12, name: "PT Logistic Sentosa" },
        type: "purchase-order",
        status: "pending",
        amount: 5200000,
        remaining: 5200000,
        description: "Pemesanan alat produksi",
      },
      {
        reference_id: 17,
        reference_type: "journal-entry",
        transaction_date: new Date("2025-03-17"),
        transaction_due_date: new Date("2025-03-17"),
        transaction_number: "JE-002",
        contact: { id: 0, name: "System" },
        type: "journal-entry",
        status: "approved",
        amount: 900000,
        remaining: 0,
        description: "Penyesuaian penyusutan",
      },
      {
        reference_id: 18,
        reference_type: "receive-money",
        transaction_date: new Date("2025-03-18"),
        transaction_due_date: new Date("2025-03-18"),
        transaction_number: "RM-002",
        contact: { id: 13, name: "Walk In Customer" },
        type: "receive-money",
        status: "completed",
        amount: 150000,
        remaining: 0,
        description: "Penjualan tunai",
      },
      {
        reference_id: 19,
        reference_type: "expense",
        transaction_date: new Date("2025-03-19"),
        transaction_due_date: new Date("2025-03-19"),
        transaction_number: "EXP-003",
        contact: { id: 14, name: "Pertamina" },
        type: "expense",
        status: "paid",
        amount: 300000,
        remaining: 0,
        description: "Bensin kendaraan operasional",
      },
      {
        reference_id: 20,
        reference_type: "sales-invoice",
        transaction_date: new Date("2025-03-20"),
        transaction_due_date: new Date("2025-04-20"),
        transaction_number: "INV-004",
        contact: { id: 15, name: "PT Digital Solusi" },
        type: "sales-invoice",
        status: "draft",
        amount: 5100000,
        remaining: 5100000,
        description: "Penjualan software lisensi",
      },
    ],
    pagination: {
      current_page: 1,
      first_page_url: "https://api.example.com?page=1",
      from: 1,
      last_page: 1,
      last_page_url: "https://api.example.com?page=2",
      links: [
        { url: null, label: "&laquo; Previous", page: null, active: false },
        {
          url: "https://api.example.com?page=1",
          label: "1",
          page: 1,
          active: true,
        },
        { url: null, label: "Next &raquo;", page: null, active: false },
      ],
      next_page_url: null,
      path: "https://api.example.com",
      per_page: 10,
      prev_page_url: null,
      to: 10,
      total: 10,
    },
  };

  return {
    loading: !data && !error,
    data: data?.data ?? DUMMY_DATA.data,
    pagination: data?.pagination ?? DUMMY_DATA.pagination,
    error,
    search,
    setSearch: onSetSearch,
    pageNum,
    setPageNum,
    pageLimit,
    setPageLimit,
  };
}
